In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("clear_data.csv")

In [3]:
df

,Unnamed: 0,CIS,Тип,Название компетенции,Name of competence,Статус компетенции,Блок компетенций
0,1,E57,WSE,Администрирование отеля,Hotel receptioning,1) Основная,Сфера услуг
1,3,8,WSI,Архитектурная обработка камня,Architectural Stonemasonry,1) Основная,технологии
2,6,17,WSI,Веб-дизайн и разработка,Web Technologies,1) Основная,технологии
3,7,R56,RU,Ветеринария,Veterinary,1) Основная,Сфера услуг
4,8,R1,RU,Видеопроизводство,Video Production,1) Основная,Творчество и дизайн
...,...,...,...,...,...,...,...
176,9,T32,RU,Цифровой модельер,Digital fashion designer,3) Кандидат в\rпрезентационную,Творчество и дизайн
177,10,T5,RU,Эксплуатация грузового речного\rтранспорта,Operation of river freight transport,3) Кандидат в\rпрезентационную,Транспорт и логистика
178,11,T75,RU,Эксплуатация сервисных роботов,Operation of service robots,3) Кандидат в\rпрезентационную,Производство и инженерные\rтехнологии
179,12,R61,RU,Электрослесарь подземный,Underground Electrician,3) Кандидат в\rпрезентационную,Производство и инженерные\rтехнологии
180,13,T80,RU,Технология энергоаудита,Energy audit technology,3) Кандидат в\rпрезентационную,Производство и инженерные\rтехнологии

       Unnamed: 0
count  181.000000
mean     9.215470
std      5.749684
min      0.000000
25%      4.000000
50%      9.000000
75%     14.000000
max     24.000000